name: release

on:
  # Publishes packages on release (the Rhino version should not be
  # changed to '-SNAPSHOT' before creating the release in Github).
  release:
    types: [published]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Publish
      run: >-
        git submodule init
        git submodule update
        ./gradlew test
    - name: Upload Artifact
      if: "!startsWith(github.ref, 'refs/tags/v')"
      uses: nanoufo/action-upload-artifacts-and-release-assets@v1.4
      with:
        path: |
          buildGradle/libs/*.jar
